services:
  data-analysis-tools:
    build: .
    ports:
      - "5003:5003"
    volumes:
      - ./uploads:/app/uploads
      - ./static:/app/static
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
      - PYTHONPATH=/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:5003/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 